- src/nodes/jambonz.html
> fixed JSON.stringify on a circular object

- src/nodes/jambonz.js
> Change Teams object to return body correctly

- package.json
- src/nodes/jambonz.html
- src/nodes/jambonz.js
Added the new joinMuted feature to the conference and LCC nodes
Added conf_hold to LCC
Couple of bug fixes
> Fixes and Updates

- src/nodes/create_call.html
- src/nodes/create_call.js
- log API response body
- support getting webhook urls from other sources
- fix outgoing payload
- update node documentation
> fix create call node

- src/nodes/create_call.html
- src/nodes/create_call.js
- src/nodes/create_sms.html
- src/nodes/create_sms.js
Tune the create_sms node to follow the same logic as the create_call node
> make create nodes identical

- src/nodes/get_calls.html
- src/nodes/get_calls.js
Support for [https://github.com/jambonz/jambonz-api-server/pull/153](https://github.com/jambonz/jambonz-api-server/pull/153)
> support filtering for get_calls node

- src/nodes/gather.js
This PR fixes a minor bug in the gather node where the FinishOnKey didn't get set properly.
> Fix bug with finish key in gather node

- src/nodes/lcc.html
- src/nodes/lcc.js
- src/nodes/libs.js
- LLC node now can be used to control call recording for ongoing calls
- Some issues were fixes
- Better LLC request logging
> Extend live call control

- src/utils/http-helpers.js
Fix node crash in case jambonz API is not reachable
> fix possible crash

- src/nodes/dequeue.js
Changing the `timeout` payload type.
> dequeue: property timeout has invalid data type

- resources/editor.js
Fix for https://github.com/jambonz/node-red-contrib-jambonz/issues/34
> Fix voice dropdown selection

- src/nodes/dial.js
Fixes a bug introduced with the 2.4.1 changes on the dial verb resulting in dest and type being undefined
I HAVE NOT bumped the version in this PR, should be 2.4.2
> Fix for bug in dial update

- src/nodes/libs.js
Removes the global and flow object from the msg object when mustache rendering is used
> Fix for mustache

- src/nodes/dial.html
- src/nodes/dial.js
> Fix dial node regression

- src/nodes/dial.html
- src/nodes/dial.js
The dial node supports `referHook` and `callerName` options now.
> Dial node support extra options

- src/nodes/gather.html
- src/nodes/gather.js
- Solves https://github.com/jambonz/node-red-contrib-jambonz/issues/45 by adding `dtmfBargein`, `bargein`, `listenDuringPrompt` options to the node.
- Fixes `actionHook` after https://github.com/jambonz/node-red-contrib-jambonz/pull/36
> Gather node

- src/nodes/sip-request.html
- src/nodes/sip-request.js
Make _sip-request_ node great again
> Sip Request: fixes for sip-request node

- src/nodes/lcc.html
- src/nodes/lcc.js
- src/nodes/libs.js
- `sip_request` support added
- `redirect` now supports `child_call_hook` option
> llc node improvements

- src/nodes/conference.html
- src/nodes/conference.js
Added `actionHook` and `statusHook` properties.
Fixed `endConferenceOnExit` property.
> Improve conference node

- src/nodes/create_call.html
- src/nodes/create_call.js
Ability to specify `callerName` and `header` options on call creation.
> Create Call: support additional options

- src/nodes/create_call.html
- src/nodes/create_call.js
Support initial set of customer-supplied metadata on create call.
> create call: support tag data

- src/nodes/listen.html
- src/nodes/listen.js
Support basic auth and additional options implemented
> fix listen node

- src/nodes/lcc.html
- src/nodes/lcc.js
Implement https://github.com/jambonz/jambonz-feature-server/pull/438
> llc for transcribe

- src/nodes/play.html
Fix input styling, won't break legacy logic
> fix input type

- src/nodes/config.html
- src/nodes/config.js
Config node now supports `listen` and newly added `sipRequestWithinDialogHook` option to handle indialog SIP INFO and MESSAGE messages. Also I formatted the code a little bit.
> Improve config node

- package-lock.json
- package.json
- src/nodes/_template.js
- src/nodes/create_call.js
- src/nodes/create_sms.js
- src/nodes/get_alerts.js
- src/nodes/get_call.js
- src/nodes/get_calls.js
- src/nodes/get_recent_calls.js
- src/nodes/lcc.js
- src/nodes/libs.js
- src/utils/http-helpers.js
Migrate to **undici** from abandoned **bent** library. Provide more details on errors. Fix issue with `/_jambonz/applications/:serverId` endpoint when http request could stuck.
> migrate to fetch

- src/nodes/dial.html
- src/nodes/dial.js
Some missing instructions were added:
- anchorMedia
- onHoldHook
> support more instructions for dial

- src/nodes/create_call.html
- src/nodes/create_call.js
Ability to select required trunk on outdial
> Create call trunk

- src/nodes/create_call.html
Fixes work done by https://github.com/jambonz/node-red-contrib-jambonz/pull/76.
Next time will be more careful while submitting PR.
> fix create call template

- src/nodes/lcc.html
- src/nodes/lcc.js
Missing break statement and better input validation(get rid of silly node errors)
> fix: llc validation and missing break

- src/nodes/dial.html
- src/nodes/dial.js
- src/nodes/lcc.js
Closes https://github.com/jambonz/node-red-contrib-jambonz/issues/92 and https://github.com/jambonz/node-red-contrib-jambonz/issues/91
> Add requested features

- src/nodes/lcc.html
- src/nodes/lcc.js
- src/nodes/libs.js
Add the Dub verb to Live Call Control,
NOTE: This will only work with jambonz servers that have been updated to 0.9.3 as LCC Dub requires the fix in https://github.com/jambonz/jambonz-feature-server/pull/974
> Feature LCC dub

- src/nodes/tag.js
Fixes bug described https://github.com/jambonz/node-red-contrib-jambonz/issues/98 and additionally i have added try/catch block around `JSON.parse() ` since the method could throw an exception and kill the node process.
> Tag: clone object and fix possible crash

- src/nodes/dial.html
Currently the dial music type could not be changed. Fixing it
> Dial music node type

- package.json
- src/nodes/alert.html
- src/nodes/alert.js
> Alert verb

- resources/editor.js
- src/nodes/auth.html
- src/nodes/auth.js
- src/nodes/create_call.js
- src/nodes/get_alerts.js
- src/nodes/get_call.js
- src/nodes/get_calls.js
- src/nodes/get_recent_calls.js
- src/nodes/lcc.js
> make auth node use typed inputs
